//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Notices
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatronNote
    {
        public int PatronID { get; set; }
        public string NonBlockingStatusNotes { get; set; }
        public string BlockingStatusNotes { get; set; }
        public Nullable<System.DateTime> NonBlockingStatusNoteDate { get; set; }
        public Nullable<System.DateTime> BlockingStatusNoteDate { get; set; }
        public Nullable<int> NonBlockingBranchID { get; set; }
        public Nullable<int> NonBlockingUserID { get; set; }
        public Nullable<int> NonBlockingWorkstationID { get; set; }
        public Nullable<int> BlockingBranchID { get; set; }
        public Nullable<int> BlockingUserID { get; set; }
        public Nullable<int> BlockingWorkstationID { get; set; }
    
        public virtual Organization Organization { get; set; }
        public virtual Organization Organization1 { get; set; }
        public virtual Patron Patron { get; set; }
    }
}
