//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Notices
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PolarisEntities : DbContext
    {
        public PolarisEntities()
            : base("name=PolarisEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<PatronRegistration> PatronRegistrations { get; set; }
        public virtual DbSet<Patron> Patrons { get; set; }
        public virtual DbSet<RecordSet> RecordSets { get; set; }
        public virtual DbSet<Organization> Organizations { get; set; }
        public virtual DbSet<PatronNote> PatronNotes { get; set; }
        public virtual DbSet<CLC_Custom_SMS_Group> CLC_Custom_SMS_Group { get; set; }
        public virtual DbSet<CLC_Custom_SMS_Queue> CLC_Custom_SMS_Queue { get; set; }
    }
}
