//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Notices {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class BounceRecordSets {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BounceRecordSets() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Notices.Resources.BounceRecordSets", typeof(BounceRecordSets).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 38043.
        /// </summary>
        public static string ALE {
            get {
                return ResourceManager.GetString("ALE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 38069.
        /// </summary>
        public static string BEX {
            get {
                return ResourceManager.GetString("BEX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 38045.
        /// </summary>
        public static string CLCE {
            get {
                return ResourceManager.GetString("CLCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 38065.
        /// </summary>
        public static string CML {
            get {
                return ResourceManager.GetString("CML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 38049.
        /// </summary>
        public static string FCL {
            get {
                return ResourceManager.GetString("FCL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 38047.
        /// </summary>
        public static string GHP {
            get {
                return ResourceManager.GetString("GHP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 38071.
        /// </summary>
        public static string LON {
            get {
                return ResourceManager.GetString("LON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 38051.
        /// </summary>
        public static string MPC {
            get {
                return ResourceManager.GetString("MPC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 38053.
        /// </summary>
        public static string MPL {
            get {
                return ResourceManager.GetString("MPL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 38055.
        /// </summary>
        public static string PCL {
            get {
                return ResourceManager.GetString("PCL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 38057.
        /// </summary>
        public static string PPL {
            get {
                return ResourceManager.GetString("PPL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 38061.
        /// </summary>
        public static string SPL {
            get {
                return ResourceManager.GetString("SPL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 38067.
        /// </summary>
        public static string UAPL {
            get {
                return ResourceManager.GetString("UAPL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 38059.
        /// </summary>
        public static string WAG {
            get {
                return ResourceManager.GetString("WAG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 38063.
        /// </summary>
        public static string WL {
            get {
                return ResourceManager.GetString("WL", resourceCulture);
            }
        }
    }
}
