//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NoticeSuite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dialout_Strings
    {
        public int StringID { get; set; }
        public int OrganizationID { get; set; }
        public int StringTypeID { get; set; }
        public string Value { get; set; }
    
        public virtual Dialout_String_Types Dialout_String_Types { get; set; }
    }
}
