//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NoticeSuite.Data {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Internal {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Internal() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NoticeSuite.Data.Internal", typeof(Internal).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calls already in process.
        /// </summary>
        public static string AlreadyRunning {
            get {
                return ResourceManager.GetString("AlreadyRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polaris API Service is not working..
        /// </summary>
        public static string ApiDown {
            get {
                return ResourceManager.GetString("ApiDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} patrons called..
        /// </summary>
        public static string CalledPatronCountPost {
            get {
                return ResourceManager.GetString("CalledPatronCountPost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calling {0} patrons.
        /// </summary>
        public static string CalledPatronCountPre {
            get {
                return ResourceManager.GetString("CalledPatronCountPre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call placed.
        /// </summary>
        public static string CallPlaced {
            get {
                return ResourceManager.GetString("CallPlaced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelling {0} calls that were in process..
        /// </summary>
        public static string CancellingCalls {
            get {
                return ResourceManager.GetString("CancellingCalls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closed today..
        /// </summary>
        public static string ClosedToday {
            get {
                return ResourceManager.GetString("ClosedToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not a valid day of the week. Falling back to weekend hours..
        /// </summary>
        public static string DayOfWeekFail {
            get {
                return ResourceManager.GetString("DayOfWeekFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty callsid, using fallback..
        /// </summary>
        public static string EmptyCallSid {
            get {
                return ResourceManager.GetString("EmptyCallSid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello, you have holds available for pickup or items overdue, please contact the library for more information. Thank you for using the library. Goodbye..
        /// </summary>
        public static string FallbackPhoneMessage {
            get {
                return ResourceManager.GetString("FallbackPhoneMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect key supplied. {0} does not match required value..
        /// </summary>
        public static string IncorrectKey {
            get {
                return ResourceManager.GetString("IncorrectKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No patrons successfully called for holds yet today, continuing dialout..
        /// </summary>
        public static string NoHoldCallsYet {
            get {
                return ResourceManager.GetString("NoHoldCallsYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No notifications to load, exitting..
        /// </summary>
        public static string NoNotifications {
            get {
                return ResourceManager.GetString("NoNotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing {0} notices..
        /// </summary>
        public static string NoticesProcessedCount {
            get {
                return ResourceManager.GetString("NoticesProcessedCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notice successfully updated..
        /// </summary>
        public static string NotificationUpdateSuccess {
            get {
                return ResourceManager.GetString("NotificationUpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outside run hours..
        /// </summary>
        public static string OutsideRunHours {
            get {
                return ResourceManager.GetString("OutsideRunHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patron already called for hold.
        /// </summary>
        public static string PatronAlreadyCalledHold {
            get {
                return ResourceManager.GetString("PatronAlreadyCalledHold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test call please ignore.
        /// </summary>
        public static string TestCallDetailsMessage {
            get {
                return ResourceManager.GetString("TestCallDetailsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempting to build phone message..
        /// </summary>
        public static string TwimlBuildStart {
            get {
                return ResourceManager.GetString("TwimlBuildStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create phone message, using fallback..
        /// </summary>
        public static string TwimlFail {
            get {
                return ResourceManager.GetString("TwimlFail", resourceCulture);
            }
        }
    }
}
