//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NoticeSuite.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class NoticeEntities : DbContext
    {
        private NoticeEntities()
            : base("name=NoticeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Dialout_String_Types> Dialout_String_Types { get; set; }
        public virtual DbSet<Dialout_Strings> Dialout_Strings { get; set; }
        public virtual DbSet<PolarisNotification> PolarisNotifications { get; set; }
        public virtual DbSet<Dialin_Ignore_List> Dialin_Ignore_List { get; set; }
        public virtual DbSet<Dialin_Patrons> Dialin_Patrons { get; set; }
        public virtual DbSet<SMS_Queue> SMS_Queue { get; set; }
        public virtual DbSet<PolarisOrganization> PolarisOrganizations { get; set; }
        public virtual DbSet<SMS_Group> SMS_Group { get; set; }
        public virtual DbSet<RecordSets> RecordSets { get; set; }
        public virtual DbSet<RecordSetTypes> RecordSetTypes { get; set; }
        public virtual DbSet<TodaysHoldCall> TodaysHoldCalls { get; set; }
        public virtual DbSet<EmailDomain> EmailDomains { get; set; }
    
        public virtual ObjectResult<GetClosedDates_Result> GetClosedDates(Nullable<int> orgid)
        {
            var orgidParameter = orgid.HasValue ?
                new ObjectParameter("orgid", orgid) :
                new ObjectParameter("orgid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetClosedDates_Result>("GetClosedDates", orgidParameter);
        }
    
        public virtual ObjectResult<GetCheckedOutItems_Result> GetCheckedOutItems(Nullable<int> patronId, Nullable<int> itemType)
        {
            var patronIdParameter = patronId.HasValue ?
                new ObjectParameter("patronId", patronId) :
                new ObjectParameter("patronId", typeof(int));
    
            var itemTypeParameter = itemType.HasValue ?
                new ObjectParameter("itemType", itemType) :
                new ObjectParameter("itemType", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetCheckedOutItems_Result>("GetCheckedOutItems", patronIdParameter, itemTypeParameter);
        }
    }
}
