//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NoticeSuite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatronRegistration
    {
        public int PatronID { get; set; }
        public Nullable<short> LanguageID { get; set; }
        public string NameFirst { get; set; }
        public string NameLast { get; set; }
        public string NameMiddle { get; set; }
        public string NameTitle { get; set; }
        public string NameSuffix { get; set; }
        public string PhoneVoice1 { get; set; }
        public string PhoneVoice2 { get; set; }
        public string PhoneVoice3 { get; set; }
        public string EmailAddress { get; set; }
        public string Password { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public Nullable<System.DateTime> ExpirationDate { get; set; }
        public Nullable<System.DateTime> AddrCheckDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string User1 { get; set; }
        public string User2 { get; set; }
        public string User3 { get; set; }
        public string User4 { get; set; }
        public string User5 { get; set; }
        public string Gender { get; set; }
        public Nullable<System.DateTime> Birthdate { get; set; }
        public Nullable<System.DateTime> RegistrationDate { get; set; }
        public string FormerID { get; set; }
        public byte ReadingList { get; set; }
        public string PhoneFAX { get; set; }
        public Nullable<int> DeliveryOptionID { get; set; }
        public Nullable<int> StatisticalClassID { get; set; }
        public bool CollectionExempt { get; set; }
        public string AltEmailAddress { get; set; }
        public bool ExcludeFromOverdues { get; set; }
        public string SDIEmailAddress { get; set; }
        public Nullable<int> SDIEmailFormatID { get; set; }
        public Nullable<bool> SDIPositiveAssent { get; set; }
        public Nullable<System.DateTime> SDIPositiveAssentDate { get; set; }
        public bool DeletionExempt { get; set; }
        public string PatronFullName { get; set; }
        public bool ExcludeFromHolds { get; set; }
        public bool ExcludeFromBills { get; set; }
        public int EmailFormatID { get; set; }
        public string PatronFirstLastName { get; set; }
        public string Username { get; set; }
        public Nullable<System.DateTime> MergeDate { get; set; }
        public Nullable<int> MergeUserID { get; set; }
        public string MergeBarcode { get; set; }
        public Nullable<bool> EnableSMS { get; set; }
        public Nullable<int> RequestPickupBranchID { get; set; }
        public Nullable<int> Phone1CarrierID { get; set; }
        public Nullable<int> Phone2CarrierID { get; set; }
        public Nullable<int> Phone3CarrierID { get; set; }
        public Nullable<int> eReceiptOptionID { get; set; }
        public Nullable<byte> TxtPhoneNumber { get; set; }
        public Nullable<bool> ExcludeFromAlmostOverdueAutoRenew { get; set; }
        public Nullable<bool> ExcludeFromPatronRecExpiration { get; set; }
        public Nullable<bool> ExcludeFromInactivePatron { get; set; }
    
        public virtual Patron Patron { get; set; }
        public virtual Organization Organization { get; set; }
    }
}
