//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NoticeSuite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PolarisOrganization
    {
        public int OrganizationID { get; set; }
        public Nullable<int> ParentOrganizationID { get; set; }
        public int OrganizationCodeID { get; set; }
        public string Name { get; set; }
        public string Abbreviation { get; set; }
        public int SA_ContactPersonID { get; set; }
        public int CreatorID { get; set; }
        public Nullable<int> ModifierID { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<System.DateTime> ModificationDate { get; set; }
        public string DisplayName { get; set; }
    }
}
