//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NoticeSuite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecordSet
    {
        public RecordSet()
        {
            this.Patrons = new HashSet<Patron>();
        }
    
        public int RecordSetID { get; set; }
        public string Name { get; set; }
        public int ObjectTypeID { get; set; }
        public int CreatorID { get; set; }
        public Nullable<int> ModifierID { get; set; }
        public Nullable<int> OrganizationOwnerID { get; set; }
        public System.DateTime CreationDate { get; set; }
        public Nullable<System.DateTime> ModificationDate { get; set; }
        public string Note { get; set; }
    
        public virtual ICollection<Patron> Patrons { get; set; }
        public virtual Organization Organization { get; set; }
    }
}
