//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NoticeSuite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TodaysHoldCall
    {
        public int PatronID { get; set; }
        public int ReportingOrgId { get; set; }
        public int ReportingLibraryID { get; set; }
    }
}
